---
title: "Training-set Exploration"
author: "Salma Elshahawy"
date: "`r Sys.Date()`"
output:
  pdf_document:
    includes:
      in_header: header.tex
    number_sections: yes
    toc: yes
    toc_depth: 2
  html_document:
    toc: yes
    toc_depth: '2'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Hmisc)
```



```{r message=FALSE, warning=FALSE}
dataset <- read.csv(
  "https://raw.githubusercontent.com/salma71/Data_621/master/HW_1/datasets/moneyball-training-data.csv",
  stringsAsFactors = FALSE)
```

```{r}
dim(dataset)
```
```{r}
# list types for each attribute
sapply(dataset, class)
```
```{r}
library(kableExtra)
# take a peek at the first 5 rows of the data
kableExtra::kbl(head(dataset[2:17], 40), booktabs = T) %>%
  kable_styling(latex_options = c('striped','scale_down')) %>%
  landscape()
```

We can confirm that the scales for the attributes are all over the place because of the differing units. We may benefit from some transforms later on.
```{r message=FALSE, warning=FALSE, paged.print=TRUE}
quick_summary <- function(df){
  df %>%
    summary() %>%
    kable() %>%
    kable_styling(latex_options = 'striped') %>%
    landscape()
}

quick_summary(dataset[2:7])
quick_summary(dataset[8:12])
quick_summary(dataset[13:15])
```

Use Hmisc library to derive the p-value correlation matrix

Formatting the correlation matrix table 
```{r}
# ++++++++++++++++++++++++++++
# flattenCorrMatrix
# ++++++++++++++++++++++++++++
# cormat : matrix of the correlation coefficients
# pmat : matrix of the correlation p-values
flattenCorrMatrix <- function(cormat, pmat) {
  ut <- upper.tri(cormat)
  data.frame(
    row = rownames(cormat)[row(cormat)[ut]],
    column = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut],
    p = pmat[ut]
    )
}

res2<-rcorr(as.matrix(dataset))
flattenCorrMatrix(res2$r, res2$P)
```


